# Generated by Django 3.1.2 on 2023-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_delete_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
