articles=[
    {"name":"Ivan_article",
     "number":"1",
     "slug":"Article1"
     },
    {"name":"valdez_article",
     "number":"2",
      "slug":"Article2"
     },
    {
        "name":"jordan_article",
     "number":"3",
      "slug":"Article3"
    }
]